import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Alzayat website - موقع مدرسة د.محمد حسن الزيات",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>{children}</>
  );
}
