import type { Metadata } from "next";
import "./globals.css";

// TODO: update metadata
export const metadata: Metadata = {
  title: "Tanzania charity foundation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>{children}</>
  );
}
